Repository DhanushNehru/board, pull requests merged in 2022-10, with the labels that each got.

#6 Make flexible with mobile devices [fixes #5]
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest-accepted

#29 Changed default Board Color and Pen Color
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 Updated readme as default board color is white now.
  README.md
Labels: hacktoberfest
